# Generated by Django 4.2.17 on 2025-01-06 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCritContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(max_length=200)),
                ('contact_field', models.TextField()),
                ('contact_created_on', models.DateTimeField(auto_now_add=True)),
                ('contact_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamecrit_contact', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
