# Generated by Django 4.2.17 on 2025-02-02 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamecrit_contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecritcontact',
            name='contact_name',
        ),
    ]
