# Generated by Django 4.2.17 on 2025-01-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamecrit_post', '0004_rename_body_comment_comment_field_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
