# Generated by Django 4.2.17 on 2025-01-14 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamecrit_post', '0006_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gamecrit_post_blog_like',
            field=models.ManyToManyField(blank=True, related_name='gamecrit_post_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
