# Generated by Django 4.2.17 on 2025-01-14 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamecrit_post', '0007_post_gamecrit_post_blog_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='gamecrit_post_blog_like',
            new_name='gamecrit_post_blog_likes',
        ),
    ]
