# Generated by Django 4.2.17 on 2025-01-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecrit_post', '0011_remove_post_post_private_post_alt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='youtube_link',
            field=models.URLField(max_length=300),
        ),
    ]
